# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    # Fix the last lines' trailing whitespace before correcting that they exist.
  - id: trailing-whitespace
  - id: end-of-file-fixer

  - id: check-added-large-files
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: no-commit-to-branch  # main
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.3.1
  hooks:
  - id: forbid-crlf
  - id: forbid-tabs
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
- repo: https://github.com/rubocop/rubocop
  rev: v1.39.0
  hooks:
  - id: rubocop
- repo: local
  hooks:
  - id: php-cs-fixer
    entry: php-cs-fixer fix --config .php-cs-fixer.dist.php
    language: system
    name: php-cs-fixer
    types: [php]
